import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styled from "@emotion/styled";
import { List, ListItem, ListItemButton, ListItemText } from "@mui/material";
import apolloClient from "../apollo-client";
import { gql } from "@apollo/client";

const Container = styled.div`
  display: grid;
  height: 100vh;
  grid-template-columns: 0.3fr 0.7fr;
  grid-template-rows: 0.12fr 0.88fr;
  grid-template-areas:
    "nav nav"
    "sidebar main";
  text-align: center;
  transition: all 0.25s ease-in-out;
  @media (max-width: 550px) {
    grid-template-columns: 1fr;
    grid-template-rows: 0.4fr 0.4fr 2.2fr;
    grid-template-areas:
      "nav"
      "sidebar"
      "main"
      "content";
  }
  color: white;
`;

const NavBar = styled.nav`
  background: #3a3a55;
  grid-area: nav;
  padding: 0.25rem;
`;
const Main = styled.main`
  background: #1f2128;
  color: white;
  grid-area: main;
  padding: 0.25rem;
`;
const SideBar = styled.div`
  background: #9aaab7;
  grid-area: sidebar;
  padding: 0.25rem;
`;

interface IProps {
  foodCategories: string[];
}

interface QueryResponse {
  foodCategories: {
    name: string;
  }[];
  foods: {
    name: string
    price: number
    description: string
    stock: number
  }[];
}

export const getStaticProps: GetStaticProps<IProps> = async () => {
  const { data: {foodCategories} } = await apolloClient.query<QueryResponse>({
    query: gql`
      query FoodCategories {
        foodCategories {
          name
        }
      }
    `,
  });

  const { data: {foods} } = await apolloClient.query<QueryResponse>({
    query: gql`
      query Foods($categoryName: String!  ) {
        foods(categoryName: $categoryName) {
          name
          price
          stock
          description
        }
      }
    `,
    variables: {
      categoryName: foodCategories[0].name
    }
  });

  return {
    props: {
      foodCategories: foodCategories.map(({ name }) => name),
      foods
    },
  };
};

const Home: NextPage<IProps> = ({foodCategories, foods}) => {
  return (
    <div>
      <Head>
        <title>Shopping Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <NavBar>Logo Mclloyd picture Shopping Cart</NavBar>
        <SideBar>
          <List>
            {foodCategories.map((text, index) => (
              <ListItem key={text} disablePadding>
                <ListItemButton>
                  <ListItemText primary={text} />
                  
                </ListItemButton>
              </ListItem>
            ))}
          </List>
        </SideBar>
        <Main>
        <List>
            {foods.map((food) => (
              <ListItem key={food.name} disablePadding>
                  <span>{food.name}</span>
                  <span>price: {food.price}</span> 
                  <span>stock: {food.stock}</span> 
                <ListItemButton>
                  <ListItemText primary={"Buy"} />
                </ListItemButton>
              </ListItem>
            ))}
          </List>
        </Main>
      </Container>
    </div>
  );
};

export default Home;
